### ISSUE TITLE
Do not use Genetive "s" when name ends with "s" in Sprechstunden-Rooms

### ISSUE THREAD

**Issue by dst97** [Rdeisenroth/Rubot2#11]
If the name of a tutor ends with `s`, there must not be an `s` at the end of name in the genetive form. Instead a `'` must be used. For example, the name of `Yanarss FOP-Sprechstunde` should be `Yanars' FOP-Sprechstunde`.

**Comment by Rdeisenroth** [comment]
I agree, i will adjust the default value.

**Comment by dst97** [comment]
`s` should still be used if the name does not end with s.
